<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">


     <link name = "base_footprint">
     </link>


     
    <link name = "base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <material name="orange" />
        </visual>
    </link>

    <link name="forearm_link">
            <visual>
                <geometry>
                    <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/>
                </geometry>
                <origin xyz="0 0 ${(cylinder_length/2)}" rpy="0 0 0"/>
                <material name="yellow"/>
            </visual>
    </link>

    <link name="hand_link">
            <visual>
                <geometry>
                    <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/>
                </geometry>
                <origin xyz="0 0 ${cylinder_length/2}" rpy="0 0 0"/>
                <material name="orange"/>
            </visual>
    </link>






    
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    
    <joint name="base_forearm_joint" type="revolute">
        <parent link="base_link"/>
        <child link="forearm_link"/>
        <origin xyz="0 0 ${(base_height/2)}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="1000.0" lower="0" upper="${pi}" velocity="100"/>
    </joint>

    
    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link"/>
        <child link="hand_link"/>
        <origin xyz="0 0 ${cylinder_length}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="1000.0" lower="0" upper="${pi}" velocity="100"/>
    </joint>

</robot>